version: '3'

services:
  db:
    image: postgres:13-alpine
    env_file:
    - ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code
      - /var/www/images:/code/backend/images
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /code/backend

  migration:
    build:
      context: ./backend
    command: python manage.py migrate --noinput
    depends_on:
      - db
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres-data: