# Generated by Django 4.1.7 on 2023-07-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Оформлен'), (2, 'Оплачен'), (3, 'В пути'), (4, 'Доставлен'), (5, 'Отменен'), (6, 'Товар не в наличии')], default=1),
        ),
    ]
