# Generated by Django 4.1.7 on 2023-05-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Оформлен'), (2, 'Оплачен'), (3, 'В пути'), (4, 'Доставлен'), (5, 'Отменен')], default=1),
        ),
    ]
